apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudgit
  labels:
    app: cloudgit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudgit
  template:
    metadata:
      labels:
        app: cloudgit
    spec:
      containers:
      - name: cloudgit
        image: docker.io/jinucat/cloudgit:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cloudgit-service
spec:
  selector:
    app: cloudgit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
